import { Link, useParams } from 'react-router-dom';
import { Badge } from '../../components/Badge';
import { MetricNumber } from '../../components/MetricNumber';
import { PageState } from '../../components/PageState';
import { StatTile } from '../../components/StatTile';
import { ChampionAscent } from '../../exhibits/ChampionAscent';
import { ResearchTree } from '../../exhibits/ResearchTree';
import { compact, duration, recipeSummary, resolveRecipe, totalTokens } from '../../lib/format';
import { useSnapshot } from '../../lib/data/queries';
import './Overview.css';

export function Overview() { const {orchId}=useParams(); const q=useSnapshot(orchId); const s=q.data; if(!s)return <PageState loading={q.isLoading} error={q.error}/>; const baseline=s.experiments.find(e=>e.is_baseline)?.metrics.gini_weighted??null; const final=s.playoff?.final ? s.playoff.finalists.find(f=>f.delegation_id===s.playoff!.final!.delegation_id) : null; const champion=s.experiments.find(e=>e.experiment_id===(final?.experiment_id??s.champion_timeline.at(-1)?.new_champion_id)); const totals=s.telemetry_summary.totals; const decided=s.delegations.reduce((n,d)=>n+d.budget.decided,0); const championLabel=recipeSummary(resolveRecipe(s.experiments,champion))??final?.model_family??champion?.model_family??'Campaign champion'; return <main className="page overview">
  <section className="overview-hero panel"><div><span className="eyebrow">Final champion · {s.campaign.status}</span><h1>{championLabel}</h1><p className="mono">{final?.experiment_id??champion?.experiment_id}</p><Link to="#playoff"><Badge kind="promote">{s.playoff?.decision_mode??'no playoff'} verdict</Badge></Link></div><StatTile label="Final gini" value={<MetricNumber value={final?.gini_weighted??champion?.metrics.gini_weighted??null}/>} /><StatTile label="vs baseline" value={<MetricNumber kind="lift" value={baseline==null?null:(final?.gini_weighted??champion?.metrics.gini_weighted??0)-baseline}/>} /><StatTile label="Dataset" value={`${s.campaign.dataset} / ${s.campaign.target_mode}`} /><StatTile label="Duration" value={duration((new Date(s.campaign.ended_at??s.campaign.created_at).getTime()-new Date(s.campaign.created_at).getTime())/60000)} /><StatTile label="Orchestrator" value={s.campaign.orchestrator_model} /></section>
  <ChampionAscent orchId={s.campaign.orch_id} experiments={s.experiments} championTimeline={s.champion_timeline} delegations={s.delegations} notes={s.notes}/>
  <div className="overview-grid"><section className="panel ledger"><header className="section-title"><div><span className="eyebrow">Budget ledger</span><h2>Cycles by delegation</h2></div></header>{s.delegations.map(d=>{const unused=Math.max(0,d.budget.committed-d.budget.used-d.budget.forfeited);return <Link className="budget-row" key={d.delegation_id} to={`/o/${orchId}/delegations/${d.delegation_id}`}><b>{d.delegation_id}</b><div className="budget-track"><i className="used" style={{flex:d.budget.used}}/><i className="forfeited" style={{flex:d.budget.forfeited}}/><i className="unused" style={{flex:unused}}/></div><span>{d.budget.used}/{d.budget.committed}{d.distress.active.length?' ✕':''}</span></Link>})}</section>
  <section className="panel cost-panel"><header className="section-title"><div><span className="eyebrow">Cost panel</span><h2>{compact(totalTokens(totals))} tokens</h2></div><Link to={`/o/${orchId}/telemetry`}>Open analytics →</Link></header><div className="cost-stack"><i className="cached" style={{flex:totals.cached_input}}/><i className="uncached" style={{flex:Math.max(0,totals.input-totals.cached_input)}}/><i className="output" style={{flex:totals.output}}/><i className="reasoning" style={{flex:totals.reasoning}}/></div><div className="stat-grid"><StatTile label="Cache hit" value={<MetricNumber kind="percent" value={s.telemetry_summary.cache_hit_rate}/>} /><StatTile label="Tokens / decision" value={compact(totalTokens(totals)/Math.max(decided,1))}/><StatTile label="Model calls" value={totals.model_calls}/><StatTile label="Tool calls" value={totals.tool_calls}/></div></section></div>
  <section className="distress-section"><header className="section-title"><div><span className="eyebrow">Distress board</span><h2>Raised flags</h2></div></header><div className="distress-grid">{s.delegations.flatMap(d=>d.distress.active.map(flag=><Link className="distress-card panel" key={`${d.delegation_id}-${flag}`} to={`/o/${orchId}/journey#chapter-${d.delegation_id}`}><Badge kind="distress">{flag}</Badge><b>{d.delegation_id}</b><p>{d.distress.detail??'Flag raised during delegation.'}</p>{d.taken_over&&<Badge kind="takeover">takeover recovered</Badge>}</Link>))}</div></section>
  <ResearchTree orchId={s.campaign.orch_id} experiments={s.experiments} delegations={s.delegations}/>
  <section className="panel playoff-panel" id="playoff"><header className="section-title"><div><span className="eyebrow">Playoff</span><h2>Final consolidation</h2></div><Badge kind="orchestrator">{s.playoff?.decision_mode??'unavailable'}</Badge></header>{s.playoff?<><div className="playoff-table">{s.playoff.finalists.map(f=><Link key={f.delegation_id} to={`/o/${orchId}/delegations/${f.delegation_id}`}><b>{f.delegation_id}</b><span>{recipeSummary(resolveRecipe(s.experiments,s.experiments.find(e=>e.experiment_id===f.experiment_id)))??f.model_family}</span><MetricNumber value={f.gini_weighted}/></Link>)}</div>{s.playoff.final&&<p className="lineage mono">{s.playoff.final.source_experiment_id} → {s.playoff.final.consolidation_experiment_id}</p>}{s.playoff.report_md&&<Link to={`/o/${orchId}/files/${s.playoff.report_md}`}>Open playoff evidence →</Link>}</>:<p>No playoff record.</p>}</section>
  </main>; }
