import { useMemo, useState } from 'react';
import { ArrowDown, ArrowUp } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Badge } from '../../components/Badge';
import { MetricNumber } from '../../components/MetricNumber';
import { StatTile } from '../../components/StatTile';
import { useIndex } from '../../lib/data/queries';
import type { IndexEntry } from '../../lib/types';
import './Hangar.css';

function tokens(entry: IndexEntry) { const t = entry.total_tokens; return t.input + t.output + t.reasoning; }
function compact(value: number) { return Intl.NumberFormat('en', { notation: 'compact', maximumFractionDigits: 2 }).format(value); }
function duration(minutes: number | null) { if (minutes == null) return '—'; const h = Math.floor(minutes / 60); const m = Math.round(minutes % 60); return h ? `${h}h ${m}m` : `${m}m`; }
function Sparkline({ values }: {values: number[]}) { if (!values.length) return <span className="empty-spark">No promotions</span>; const min = Math.min(...values), max = Math.max(...values), range = max - min || 1; const points = values.map((v,i) => `${(i / Math.max(values.length - 1, 1)) * 180},${42 - ((v-min)/range)*34}`).join(' '); return <svg className="sparkline" viewBox="0 0 180 50" role="img" aria-label="Champion gini progression"><polyline points={points} /></svg>; }
function CampaignCard({ entry }: {entry: IndexEntry}) { return <Link className="campaign-card panel" to={`/o/${entry.orch_id}`}>
  <div className="card-top"><div><span className="eyebrow mono">{entry.orch_id}</span><h2>{entry.alias || entry.dataset}</h2></div><Badge kind={entry.status === 'completed' ? 'promote' : 'takeover'}>{entry.status}</Badge></div>
  <div className="chips"><span>{entry.dataset}</span><span>{entry.target_mode}</span><span>{entry.orchestrator_model}</span></div><Sparkline values={entry.champion_spark} />
  <div className="card-stats"><StatTile label="Final gini" value={<MetricNumber value={entry.final_gini} />} /><StatTile label="Delegations" value={entry.n_delegations} /><StatTile label="Cycles" value={`${entry.cycles_used}/${entry.cycles_committed}`} /><StatTile label="Tokens" value={compact(tokens(entry))} /><StatTile label="Duration" value={duration(entry.wall_clock_minutes)} /><StatTile label="Distress" value={entry.distress_count} /></div>
  </Link>; }

type SortKey = 'final_gini'|'dataset'|'orchestrator_model'|'cycles_used'|'tokens'|'cache_hit_rate'|'wall_clock_minutes'|'distress_count'|'takeover_count';
const columns: [SortKey,string][] = [['final_gini','Final gini'],['dataset','Dataset'],['orchestrator_model','Orchestrator'],['cycles_used','Cycles'],['tokens','Tokens'],['cache_hit_rate','Cache hit'],['wall_clock_minutes','Wall clock'],['distress_count','Distress'],['takeover_count','Takeovers']];
function sortValue(entry: IndexEntry, key: SortKey): string|number { return key === 'tokens' ? tokens(entry) : entry[key] ?? -Infinity; }
function League({ entries }: {entries: IndexEntry[]}) { const [key,setKey] = useState<SortKey>('final_gini'); const [ascending,setAscending] = useState(false); const sorted = useMemo(() => [...entries].sort((a,b) => { const av=sortValue(a,key), bv=sortValue(b,key); return (typeof av === 'string' ? av.localeCompare(String(bv)) : av-Number(bv))*(ascending?1:-1); }),[entries,key,ascending]); function choose(next: SortKey) { if(next===key)setAscending(v=>!v); else {setKey(next);setAscending(next==='dataset'||next==='orchestrator_model');} }
  return <div className="league-table-wrap panel" id="league"><table className="league-table"><thead><tr><th>Orchestration</th>{columns.map(([id,label])=><th key={id}><button onClick={()=>choose(id)}>{label}{key===id?(ascending?<ArrowUp/>:<ArrowDown/>):null}</button></th>)}<th>Backends</th></tr></thead><tbody>{sorted.map(entry=><tr key={entry.orch_id}><td><Link to={`/o/${entry.orch_id}`}>{entry.alias||entry.orch_id}</Link></td><td><MetricNumber value={entry.final_gini}/></td><td><span>{entry.dataset}</span><small>not comparable across datasets</small></td><td>{entry.orchestrator_model}</td><td className="mono">{entry.cycles_used}/{entry.cycles_committed}</td><td className="mono">{compact(tokens(entry))}</td><td><MetricNumber value={entry.cache_hit_rate} kind="percent"/></td><td className="mono">{duration(entry.wall_clock_minutes)}</td><td className="mono">{entry.distress_count}</td><td className="mono">{entry.takeover_count}</td><td>{entry.backends.join(', ')}</td></tr>)}</tbody></table></div>;
}
function Scatter({ entries }: {entries: IndexEntry[]}) { const usable=entries.filter(e=>e.final_gini!=null&&tokens(e)>0); if(!usable.length)return <div className="scatter panel">No cost data</div>; const logs=usable.map(e=>Math.log10(tokens(e))), ginis=usable.map(e=>e.final_gini!); const x0=Math.min(...logs),xr=Math.max(...logs)-x0||1,y0=Math.min(...ginis),yr=Math.max(...ginis)-y0||1; return <div className="scatter panel"><div><span className="eyebrow">Cost / performance</span><h3>Tokens vs final gini</h3></div><svg viewBox="0 0 420 240" role="img" aria-label="Total tokens versus final gini scatter"><line x1="45" y1="15" x2="45" y2="205"/><line x1="45" y1="205" x2="405" y2="205"/>{usable.map((e,i)=><Link key={e.orch_id} to={`/o/${e.orch_id}`}><circle cx={45+((logs[i]-x0)/xr)*350} cy={195-((ginis[i]-y0)/yr)*170} r="7"><title>{e.orch_id}: {compact(tokens(e))} tokens, {e.final_gini?.toFixed(4)}</title></circle></Link>)}<text x="225" y="232">Total tokens (log)</text><text transform="translate(14 125) rotate(-90)">Final gini</text></svg></div>; }
export function Hangar({ leagueOnly=false }: {leagueOnly?: boolean}) { const query=useIndex(); if(query.isLoading)return <main className="page"><p>Loading flight records…</p></main>; if(query.error)return <main className="page error-state">Unable to load snapshots: {query.error.message}</main>; const entries=query.data?.orchestrations??[]; return <main className="page hangar"><header className="hangar-heading"><div><span className="eyebrow">Orchestration report archive</span><h1>{leagueOnly?'League':'Hangar'}</h1></div><span className="index-date">Index built <time>{query.data?.built_at}</time></span></header>{!leagueOnly&&<section><div className="section-heading"><h2>Campaigns</h2><span>{entries.length} snapshots</span></div><div className="campaign-grid">{entries.map(e=><CampaignCard key={e.orch_id} entry={e}/>)}</div></section>}<section className="league-section"><div className="section-heading"><div><h2>League table</h2><p>Group by dataset before comparing performance.</p></div></div><div className="league-layout"><League entries={entries}/><Scatter entries={entries}/></div></section></main>; }
