"""The campaign log — framework facts and operator commentary, kept apart.

``ORCHESTRATION_LOG.md`` is the orchestration-level sibling of ``RESEARCH_LOG.md``
and obeys the same rule: it is **generated**, never hand-edited. Two sources feed
it, and they never mix:

* **Framework-computed facts** come from ``orchestration.json`` and the
  delegation reports at render time. Nothing an agent said can change them.
* **Operator commentary** is what the orchestrator writes with
  ``orchestrate note``. It lives in ``notes.json`` and is reproduced verbatim.

Rendering is deterministic: the same manifest and the same ``notes.json`` produce
byte-identical Markdown, so the log can be regenerated at will and diffed.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from autoresearch.orchestration.manifest import (
    Orchestration,
    load_orchestration,
    log_markdown_path,
    manifest_lock,
    notes_path,
    utc_stamp,
)
from autoresearch.utils.io import read_json, write_json


#: Why an operator wrote an entry. A closed set keeps the log skimmable.
NOTE_KINDS = ("plan", "reflection", "takeover", "decision", "other")

_GENERATED_BANNER = (
    "<!-- Generated by `autoresearch orchestrate note`. Do not edit by hand: "
    "operator entries live in notes.json, facts are read from orchestration.json. -->"
)


@dataclass(frozen=True)
class Note:
    """One timestamped operator reflection."""

    timestamp: str
    kind: str
    text: str
    delegation_id: str | None = None

    def __post_init__(self) -> None:
        if self.kind not in NOTE_KINDS:
            raise ValueError(
                f"Unknown note kind {self.kind!r}; expected one of {list(NOTE_KINDS)}"
            )
        if not self.text.strip():
            raise ValueError("A note needs text; an empty reflection records nothing")

    def to_dict(self) -> dict[str, Any]:
        return {
            "timestamp": self.timestamp,
            "kind": self.kind,
            "text": self.text,
            "delegation_id": self.delegation_id,
        }

    @classmethod
    def from_dict(cls, raw: dict[str, Any]) -> "Note":
        return cls(
            timestamp=str(raw["timestamp"]),
            kind=str(raw.get("kind", "reflection")),
            text=str(raw["text"]),
            delegation_id=raw.get("delegation_id"),
        )


# ── structured storage (the source of truth) ─────────────────────────────────


def load_notes(orchestration_id: str) -> list[Note]:
    """Read every operator note, oldest first."""

    path = notes_path(orchestration_id)
    if not path.exists():
        return []
    payload = read_json(path)
    return [Note.from_dict(item) for item in payload.get("notes") or ()]


def save_notes(orchestration_id: str, notes: list[Note]) -> Path:
    path = notes_path(orchestration_id)
    write_json(path, {"notes": [note.to_dict() for note in notes]})
    return path


def append_note(
    orchestration_id: str,
    *,
    text: str,
    kind: str = "reflection",
    delegation_id: str | None = None,
    timestamp: str | None = None,
) -> Note:
    """Append one operator note and regenerate ``ORCHESTRATION_LOG.md``.

    The append and the render happen under the manifest lock, so a note written
    while a detached spawner is mutating the manifest cannot lose either write.
    """

    orch = load_orchestration(orchestration_id)
    if delegation_id is not None:
        orch.delegation(delegation_id)  # fail loudly on an unknown delegation

    note = Note(
        timestamp=timestamp or utc_stamp(),
        kind=kind,
        text=text.strip(),
        delegation_id=delegation_id,
    )
    with manifest_lock(orchestration_id):
        notes = load_notes(orchestration_id)
        notes.append(note)
        save_notes(orchestration_id, notes)
        render_campaign_log(load_orchestration(orchestration_id), notes)
    return note


# ── rendering (derived; safe to regenerate at any time) ──────────────────────


def render_campaign_log(orch: Orchestration, notes: list[Note] | None = None) -> Path:
    """Regenerate ``ORCHESTRATION_LOG.md`` from the manifest and the notes."""

    if notes is None:
        notes = load_notes(orch.orchestration_id)
    text = _render(orch, notes)
    path = log_markdown_path(orch.orchestration_id)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


def _render(orch: Orchestration, notes: list[Note]) -> str:
    lines = [
        f"# Orchestration Log — {orch.orchestration_id}",
        "",
        _GENERATED_BANNER,
        "",
        "## Campaign (framework-computed)",
        "",
        f"- Dataset: `{orch.dataset}` / target mode `{orch.target_mode}`",
        f"- Created: {orch.created_at}",
        f"- Status: {orch.status}",
        f"- Cycle budget: {orch.cycles_committed} committed of "
        f"{orch.total_cycle_budget} ({orch.cycles_remaining} remaining)",
    ]
    if orch.model_name:
        provider = orch.model_provider or "unknown"
        lines.append(f"- Orchestrator model: {provider}/{orch.model_name}")
    if orch.consolidation.run_id:
        lines.append(
            f"- Consolidation run: `{orch.consolidation.track}/{orch.consolidation.run_id}`"
        )
    lines.append("")

    lines.extend(["## Delegations (framework-computed)", ""])
    if not orch.delegations:
        lines.append("No delegations spawned yet.")
        lines.append("")
    else:
        lines.append("| id | backend | track | run | budget | status |")
        lines.append("|---|---|---|---|---|---|")
        for d in orch.delegations:
            lines.append(
                f"| {d.delegation_id} | {d.backend} | {d.track} | `{d.run_id}` | "
                f"{d.cycle_budget} | {d.status} |"
            )
        lines.append("")

    lines.extend(["## Operator log", ""])
    if not notes:
        lines.append(
            "No operator entries yet. Reflect with "
            "`autoresearch orchestrate note --text \"...\"`."
        )
        lines.append("")
    for note in notes:
        scope = f" · {note.delegation_id}" if note.delegation_id else ""
        lines.append(f"### {note.timestamp} — {note.kind}{scope}")
        lines.append("")
        lines.extend(note.text.splitlines())
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
