import { useEffect, useMemo, useRef, useState } from 'react';
import { ChevronDown, ChevronRight, Search } from 'lucide-react';
import { useVirtualizer } from '@tanstack/react-virtual';
import { Link, useLocation, useParams } from 'react-router-dom';
import { MarkdownPane } from '../../components/MarkdownPane';
import { useFile, useSnapshot } from '../../lib/data/queries';
import './FileViewer.css';

function JsonNode({ name, value, depth=0 }: {name?: string; value: unknown; depth?: number}) { const complex=value!==null&&typeof value==='object'; const [open,setOpen]=useState(depth<2); if(!complex)return <div className="json-leaf" style={{paddingLeft:depth*16}}>{name&&<span className="json-key">{name}: </span>}<span>{JSON.stringify(value)}</span></div>; const entries=Object.entries(value as object); return <div>{<button className="json-toggle" style={{paddingLeft:depth*16}} onClick={()=>setOpen(v=>!v)}>{open?<ChevronDown/>:<ChevronRight/>}<span>{name??'root'}</span><small>{Array.isArray(value)?`[${entries.length}]`:`{${entries.length}}`}</small></button>}{open&&entries.map(([key,item])=><JsonNode key={key} name={key} value={item} depth={depth+1}/>)}</div>; }
function JsonPane({ source }: {source:string}) { try{return <div className="json-pane"><JsonNode value={JSON.parse(source)}/></div>;}catch{return <pre className="text-pane">{source}</pre>;} }
function LogPane({ source }: {source:string}) { const lines=useMemo(()=>source.split('\n'),[source]); const [find,setFind]=useState(''); const parent=useRef<HTMLDivElement>(null); const matches=useMemo(()=>{if(!find)return new Set<number>();const q=find.toLowerCase();return new Set(lines.flatMap((line,i)=>line.toLowerCase().includes(q)?[i]:[]));},[find,lines]); const virtualizer=useVirtualizer({count:lines.length,getScrollElement:()=>parent.current,estimateSize:()=>22,overscan:20}); useEffect(()=>{const n=Number(location.hash.match(/^#L(\d+)$/)?.[1]);if(n>0)virtualizer.scrollToIndex(n-1,{align:'center'});},[virtualizer]); function nextMatch(){const first=[...matches][0];if(first!=null)virtualizer.scrollToIndex(first,{align:'center'});}
 return <div className="log-viewer"><div className="log-search"><Search/><input value={find} onChange={e=>setFind(e.target.value)} onKeyDown={e=>e.key==='Enter'&&nextMatch()} placeholder="Find in log"/><span>{matches.size} matches</span></div><div className="log-scroll" ref={parent}><div style={{height:virtualizer.getTotalSize(),position:'relative'}}>{virtualizer.getVirtualItems().map(row=><div key={row.key} id={`L${row.index+1}`} className={`log-line ${matches.has(row.index)?'match':''}`} style={{position:'absolute',top:0,left:0,width:'100%',height:row.size,transform:`translateY(${row.start}px)`}}><a href={`#L${row.index+1}`}>{row.index+1}</a><code>{lines[row.index]||' '}</code></div>)}</div></div></div>;
}
export function FileViewer() { const {orchId}=useParams(); const location=useLocation(); const path=decodeURIComponent(location.pathname.split('/files/')[1]??''); const snapshot=useSnapshot(orchId); const file=useFile(orchId,path); const entry=snapshot.data?.files.find(item=>item.path===path); if(snapshot.isLoading||file.isLoading)return <main className="page">Loading file…</main>; if(snapshot.error||file.error)return <main className="page error-state">Unable to load file.</main>; const source=file.data??''; return <main className="page file-page"><nav className="breadcrumbs"><Link to={`/o/${orchId}`}>{orchId}</Link><span>/</span><span>Files</span>{path.split('/').map((part,i)=><span key={`${part}-${i}`}>/ {part}</span>)}</nav><header className="file-header"><div><span className="eyebrow">{entry?.kind??'file'} · {entry?.bytes.toLocaleString()??source.length.toLocaleString()} bytes</span><h1>{path.split('/').pop()}</h1></div>{entry?.truncated&&<span className="truncated">Tail-capped snapshot</span>}</header>{entry?.kind==='markdown'||path.endsWith('.md')?<div className="file-surface markdown-file"><MarkdownPane source={source}/></div>:entry?.kind==='json'||path.endsWith('.json')?<JsonPane source={source}/>:entry?.kind==='log'||path.endsWith('.log')?<LogPane source={source}/>:<pre className="text-pane">{source}</pre>}</main>; }
