"""Milestone holdout evaluation — fires automatically on every promotion.

When a challenger is promoted, this module refits the new champion model on
the full search partition (train + search_validation) and scores it against
the milestone holdout.  The resulting report surfaces:

- Absolute Tweedie deviance on the holdout
- SV → holdout gap (overfitting signal)
- Gini and double-lift on holdout
- Calibration deciles on holdout

The holdout rows are accessed via ``load_holdout_dataset`` which requires
the ``AUTORESEARCH_MILESTONE_TOKEN`` environment variable.  If the token is
not set or the vault is absent, the evaluation is skipped with a warning
rather than crashing the promotion flow.
"""

from __future__ import annotations

import json
import traceback
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from autoresearch.config import ProjectConfig
from autoresearch.data.preprocessing import apply_claim_capping
from autoresearch.evaluation.diagnostics import compute_diagnostics
from autoresearch.evaluation.metrics import full_metric_panel
from autoresearch.models.baselines import RAW_CLAIM_COST
from autoresearch.models.dispatcher import dispatch_model
from autoresearch.utils.io import read_json, write_json


_REPORT_TEMPLATE = """\
# Milestone Holdout Report — {promotion_id}

Promotion date: {date}
Champion experiment: `{champion_id}`
Champion model family: `{model_family}`

---

## Search-validation (SV) vs Holdout comparison

| Metric | Search-validation | Holdout | SV→Holdout gap |
|--------|------------------:|--------:|---------------:|
| Tweedie deviance (p=1.5) | {sv_tweedie:.6f} | {ho_tweedie:.6f} | {gap_tweedie:+.6f} |
| Gini (weighted) | {sv_gini:.4f} | {ho_gini:.4f} | {gap_gini:+.4f} |
| Double-lift slope | {sv_dl:.4f} | {ho_dl:.4f} | {gap_dl:+.4f} |
| Pred/actual ratio | {sv_pa:.4f} | {ho_pa:.4f} | {gap_pa:+.4f} |

## Holdout calibration (predicted decile)

{calibration_table}

---

*Auto-generated by `autoresearch/milestone.py`. Token-gated read of holdout vault.*
"""


def evaluate_on_holdout(
    config: ProjectConfig,
    champion_id: str,
    promotion_id: str,
) -> dict[str, Any] | None:
    """Refit champion on train+sv, score on holdout, write report.

    Returns a summary dict on success or None if the vault is unavailable.
    The function never raises — any failure is logged and returned as a
    warning in the summary so the promotion flow is not interrupted.
    """

    report_dir = config.artifacts_dir / "milestone_reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    report_path = report_dir / f"{promotion_id}.md"
    json_path = report_dir / f"{promotion_id}.json"

    try:
        return _run_evaluation(config, champion_id, promotion_id, report_path, json_path)
    except Exception as exc:
        warning = {
            "promotion_id": promotion_id,
            "champion_id": champion_id,
            "status": "skipped",
            "reason": str(exc),
            "traceback": traceback.format_exc(),
        }
        write_json(json_path, warning)
        report_path.write_text(
            f"# Milestone Holdout Report — {promotion_id}\n\n"
            f"**Skipped**: {exc}\n\n"
            "Re-run with `autoresearch evaluate-milestone {champion_id}` after resolving.\n",
            encoding="utf-8",
        )
        return warning


def _run_evaluation(
    config: ProjectConfig,
    champion_id: str,
    promotion_id: str,
    report_path: Path,
    json_path: Path,
) -> dict[str, Any]:
    from autoresearch.data.holdout_vault import load_holdout_dataset, load_search_dataset

    # Load the champion's experiment config
    config_snapshot_path = config.artifacts_dir / "experiments" / champion_id / "config_snapshot.json"
    if not config_snapshot_path.exists():
        raise FileNotFoundError(f"Champion config snapshot not found: {config_snapshot_path}")
    snapshot = read_json(config_snapshot_path)
    exp = snapshot.get("experiment", {})

    model_family = exp.get("model_family", "regularized_linear")
    target_strategy = exp.get("target_strategy", "direct_pure_premium")
    model_cfg = exp.get("model", {})
    preprocessing = exp.get("preprocessing", {})

    cap_enabled = bool(preprocessing.get("claim_capping_enabled", config.claim_capping_enabled))
    cap_threshold = float(preprocessing.get("claim_cap_threshold", config.claim_cap_threshold))

    # Load search partition (train + sv) and holdout
    search_frame = load_search_dataset(config.processed_dir, config.agent_dataset_name)
    holdout_frame = load_holdout_dataset(config.holdout_vault_dir)

    # Load SV predictions for the gap calculation (already computed)
    sv_predictions_path = config.artifacts_dir / "experiments" / champion_id / "predictions.csv"
    sv_predictions = pd.read_csv(sv_predictions_path)
    sv_only = sv_predictions[sv_predictions["split"] == "search_validation"]

    # Apply capping to both frames
    search_frame, _ = apply_claim_capping(search_frame, claim_column=RAW_CLAIM_COST, threshold=cap_threshold, enabled=cap_enabled)
    holdout_frame, _ = apply_claim_capping(holdout_frame, claim_column=RAW_CLAIM_COST, threshold=cap_threshold, enabled=cap_enabled)

    # Build a combined split frame: all search rows train, holdout rows flagged
    split_pack = pd.read_csv(config.splits_dir / "split_pack.csv")

    # For the holdout scoring: refit on full search partition, score holdout
    # Assign all search rows to "train_full" so the model trains on everything
    search_split = split_pack[split_pack["split"].isin({"train", "search_validation"})].copy()
    search_split["split"] = "train_full"  # treat all search rows as training
    holdout_split = split_pack[split_pack["split"] == "milestone_holdout"].copy()

    combined_split = pd.concat([search_split, holdout_split], ignore_index=True)
    combined_frame = pd.concat([search_frame, holdout_frame], ignore_index=True)

    hyperparameters = {k: v for k, v in model_cfg.items() if k not in {"feature_inclusions", "feature_exclusions"}}

    # Apply feature builder if specified
    feature_builder_module = hyperparameters.pop("feature_builder_module", None)
    if feature_builder_module:
        import importlib
        builder = importlib.import_module(feature_builder_module)
        combined_frame = builder.build_features(combined_frame)

    result = _dispatch_for_milestone(
        frame=combined_frame,
        split_frame=combined_split,
        model_family=model_family,
        target_strategy=target_strategy,
        train_split="train_full",
        score_splits=("milestone_holdout",),
        hyperparameters=hyperparameters,
        feature_inclusions=model_cfg.get("feature_inclusions"),
        feature_exclusions=model_cfg.get("feature_exclusions") or None,
    )

    holdout_preds = result[result["split"] == "milestone_holdout"]
    if holdout_preds.empty:
        raise ValueError("No holdout rows in milestone predictions — check split pack")

    ho_metrics = full_metric_panel(
        holdout_preds["actual_claim_cost"],
        holdout_preds["predicted_claim_cost"],
        holdout_preds["exposure"],
        tweedie_power=config.tweedie_power,
    )
    sv_metrics = full_metric_panel(
        sv_only["actual_claim_cost"],
        sv_only["predicted_claim_cost"],
        sv_only["exposure"],
        tweedie_power=config.tweedie_power,
    )

    # Calibration on holdout
    holdout_preds_for_diag = holdout_preds.copy()
    holdout_preds_for_diag["split"] = "milestone_holdout"
    try:
        diag = compute_diagnostics(holdout_preds_for_diag, eval_split="milestone_holdout")
        cal_rows = diag.get("calibration_by_predicted_decile", [])
        cal_lines = ["| Decile | Pred PP | Actual PP | Pred/Actual |", "|--------|--------:|----------:|------------:|"]
        for row in cal_rows:
            cal_lines.append(
                f"| {row.get('decile','?')} | {row.get('mean_predicted_pure_premium',0):.4f} | "
                f"{row.get('mean_actual_pure_premium',0):.4f} | {row.get('predicted_to_actual_ratio',0):.4f} |"
            )
        calibration_table = "\n".join(cal_lines)
    except Exception:
        calibration_table = "*(calibration diagnostics unavailable)*"

    report_text = _REPORT_TEMPLATE.format(
        promotion_id=promotion_id,
        date=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        champion_id=champion_id,
        model_family=model_family,
        sv_tweedie=sv_metrics["tweedie_deviance_p15"],
        ho_tweedie=ho_metrics["tweedie_deviance_p15"],
        gap_tweedie=ho_metrics["tweedie_deviance_p15"] - sv_metrics["tweedie_deviance_p15"],
        sv_gini=sv_metrics["gini_weighted"],
        ho_gini=ho_metrics["gini_weighted"],
        gap_gini=ho_metrics["gini_weighted"] - sv_metrics["gini_weighted"],
        sv_dl=sv_metrics["double_lift_slope"],
        ho_dl=ho_metrics["double_lift_slope"],
        gap_dl=ho_metrics["double_lift_slope"] - sv_metrics["double_lift_slope"],
        sv_pa=sv_metrics["predicted_to_actual_ratio"],
        ho_pa=ho_metrics["predicted_to_actual_ratio"],
        gap_pa=ho_metrics["predicted_to_actual_ratio"] - sv_metrics["predicted_to_actual_ratio"],
        calibration_table=calibration_table,
    )
    report_path.write_text(report_text, encoding="utf-8")

    summary = {
        "promotion_id": promotion_id,
        "champion_id": champion_id,
        "model_family": model_family,
        "status": "completed",
        "search_validation_metrics": sv_metrics,
        "holdout_metrics": ho_metrics,
        "sv_to_holdout_tweedie_gap": ho_metrics["tweedie_deviance_p15"] - sv_metrics["tweedie_deviance_p15"],
        "sv_to_holdout_gini_gap": ho_metrics["gini_weighted"] - sv_metrics["gini_weighted"],
        "report_path": str(report_path),
    }
    write_json(json_path, summary)
    return summary


def _dispatch_for_milestone(
    *,
    frame: pd.DataFrame,
    split_frame: pd.DataFrame,
    model_family: str,
    target_strategy: str,
    train_split: str,
    score_splits: tuple[str, ...],
    hyperparameters: dict,
    feature_inclusions: list[str] | None,
    feature_exclusions: list[str] | None,
) -> pd.DataFrame:
    """Dispatch a model for milestone scoring without the holdout guard."""

    from autoresearch.models.dispatcher import (
        RECORD_ID, EXPOSURE, CLAIM_COST, RAW_CLAIM_COST,
    )
    from autoresearch.models.dispatcher import _call_model  # type: ignore[attr-defined]

    data = frame.merge(split_frame[["record_id", "split"]], on="record_id", how="inner")
    train = data[data["split"] == train_split].copy()
    score = data[data["split"].isin((train_split, *score_splits))].copy()
    if train.empty:
        raise ValueError(f"Training split {train_split!r} is empty")

    predicted_cost, _ = _call_model(
        model_family, target_strategy, train, score, hyperparameters,
        feature_inclusions, feature_exclusions,
    )

    preds = pd.DataFrame({
        RECORD_ID: score[RECORD_ID].to_numpy(),
        "split": score["split"].to_numpy(),
        "exposure": score[EXPOSURE].astype(float).to_numpy(),
        "actual_claim_cost": score[CLAIM_COST].astype(float).to_numpy(),
        "actual_claim_cost_uncapped": score[RAW_CLAIM_COST].astype(float).to_numpy(),
        "predicted_claim_cost": np.clip(predicted_cost, 0.0, None),
    })
    exp = preds["exposure"].clip(lower=1e-12)
    preds["actual_pure_premium"] = preds["actual_claim_cost"] / exp
    preds["predicted_pure_premium"] = preds["predicted_claim_cost"] / exp
    return preds


def manual_evaluate_on_holdout(config: ProjectConfig, experiment_id: str) -> dict[str, Any] | None:
    """Trigger milestone evaluation for any experiment (not just a promotion)."""

    promotion_id = f"manual_{experiment_id}"
    return evaluate_on_holdout(config, experiment_id, promotion_id)
