"""Milestone holdout evaluation — fires automatically on every promotion.

When a challenger is promoted, this module refits the new champion model on
the full search partition (train + search_validation) and scores it against
the milestone holdout.  The resulting report surfaces:

- Absolute Tweedie deviance on the holdout
- SV → holdout gap (overfitting signal)
- Gini and double-lift on holdout
- Calibration deciles on holdout

The active target mode is preserved from the promoted experiment: burning-cost
runs are evaluated on claim cost, while frequency runs are evaluated on claim
count/frequency.

The holdout rows are accessed via ``load_holdout_dataset`` which requires
the ``AUTORESEARCH_MILESTONE_TOKEN`` environment variable.  If the token is
not set or the vault is absent, the evaluation is skipped with a warning
rather than crashing the promotion flow.
"""

from __future__ import annotations

import json
import traceback
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd

from autoresearch.config import ProjectConfig
from autoresearch.data.preprocessing import apply_claim_capping
from autoresearch.evaluation.diagnostics import compute_diagnostics
from autoresearch.evaluation.metrics import full_metric_panel, prediction_target_columns
from autoresearch.models.dispatcher import RAW_CLAIM_COST, dispatch_model
from autoresearch.targets import BURNING_COST, target_spec
from autoresearch.experiment_registry.registry import list_artifacts
from autoresearch.utils.io import read_json, write_json


_REPORT_TEMPLATE = """\
# Milestone Holdout Report — {promotion_id}

Promotion date: {date}
Champion experiment: `{champion_id}`
Champion model family: `{model_family}`

---

Target mode: `{target_mode}`

## Search-validation (SV) vs Holdout comparison

| Metric | Search-validation | Holdout | SV→Holdout gap |
|--------|------------------:|--------:|---------------:|
| Tweedie deviance (p=1.5) | {sv_tweedie:.6f} | {ho_tweedie:.6f} | {gap_tweedie:+.6f} |
| Gini (weighted) | {sv_gini:.4f} | {ho_gini:.4f} | {gap_gini:+.4f} |
| Double-lift slope | {sv_dl:.4f} | {ho_dl:.4f} | {gap_dl:+.4f} |
| Pred/actual ratio | {sv_pa:.4f} | {ho_pa:.4f} | {gap_pa:+.4f} |

## Holdout calibration (predicted {rate_label} decile)

{calibration_table}

---

*Auto-generated by `autoresearch/milestone.py`. Token-gated read of holdout vault.*
"""


def evaluate_on_holdout(
    config: ProjectConfig,
    champion_id: str,
    promotion_id: str,
) -> dict[str, Any] | None:
    """Refit champion on train+sv, score on holdout, write report.

    Returns a summary dict on success. Vault-absent errors (missing token or
    missing holdout file) are caught and returned as a "skipped" warning so
    the promotion flow is not interrupted. Any other failure (missing model
    script, dispatch error, metric failure) writes the warning AND re-raises
    so the caller sees the problem.
    """

    report_dir = config.artifacts_dir / "milestone_reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    report_path = report_dir / f"{promotion_id}.md"
    json_path = report_dir / f"{promotion_id}.json"

    try:
        return _run_evaluation(config, champion_id, promotion_id, report_path, json_path)
    except Exception as exc:
        is_vault_absent = "AUTORESEARCH_MILESTONE_TOKEN" in str(exc)
        warning = {
            "promotion_id": promotion_id,
            "champion_id": champion_id,
            "status": "skipped",
            "reason": str(exc),
            "traceback": traceback.format_exc(),
        }
        write_json(json_path, warning)
        report_path.write_text(
            f"# Milestone Holdout Report — {promotion_id}\n\n"
            f"**Skipped**: {exc}\n\n"
            "Re-run with `autoresearch evaluate-milestone {champion_id}` after resolving.\n",
            encoding="utf-8",
        )
        if not is_vault_absent:
            raise
        return warning


def _run_evaluation(
    config: ProjectConfig,
    champion_id: str,
    promotion_id: str,
    report_path: Path,
    json_path: Path,
) -> dict[str, Any]:
    from autoresearch.data.holdout_vault import load_holdout_dataset, load_search_dataset

    # Defensive vault check — raises EnvironmentError with token name if unavailable
    try:
        holdout_frame = load_holdout_dataset(config.holdout_vault_dir)
    except (FileNotFoundError, PermissionError) as exc:
        raise EnvironmentError(
            f"AUTORESEARCH_MILESTONE_TOKEN: holdout vault unavailable — {exc}"
        ) from exc

    # Load the champion's experiment config
    config_snapshot_path = _artifact_path(config, champion_id, "config_snapshot")
    snapshot = read_json(config_snapshot_path)
    exp = snapshot.get("experiment", {})

    model_family = exp.get("model_family", "global_mean")
    target_strategy = exp.get("target_strategy", "direct_pure_premium")
    target_mode = snapshot.get("target_mode") or snapshot.get("evaluation", {}).get("target_mode") or config.target_mode
    spec = target_spec(target_mode)
    model_cfg = exp.get("model", {})
    preprocessing = exp.get("preprocessing", {})

    cap_enabled = bool(preprocessing.get("claim_capping_enabled", config.claim_capping_enabled))
    cap_threshold = float(preprocessing.get("claim_cap_threshold", config.claim_cap_threshold))

    raw_script = snapshot.get("model_script_path")
    if raw_script:
        model_script_path: Path | None = Path(raw_script)
        if not model_script_path.exists():
            raise FileNotFoundError(
                f"Model script from snapshot does not exist: {model_script_path}"
            )
    else:
        model_script_path = None

    # Load search partition (train + sv)
    search_frame = load_search_dataset(config.processed_dir, config.agent_dataset_name)

    # Load SV predictions for the gap calculation (already computed)
    sv_predictions_path = _artifact_path(config, champion_id, "predictions")
    sv_predictions = pd.read_parquet(sv_predictions_path)
    sv_only = sv_predictions[sv_predictions["split"] == "search_validation"]

    # Apply capping to both frames
    search_frame, _ = apply_claim_capping(search_frame, claim_column=RAW_CLAIM_COST, threshold=cap_threshold, enabled=cap_enabled)
    holdout_frame, _ = apply_claim_capping(holdout_frame, claim_column=RAW_CLAIM_COST, threshold=cap_threshold, enabled=cap_enabled)

    # Build a combined split frame: all search rows train, holdout rows flagged
    split_pack = pd.read_csv(config.splits_dir / "split_pack.csv")

    # For the holdout scoring: refit on full search partition, score holdout
    # Assign all search rows to "train_full" so the model trains on everything
    search_split = split_pack[split_pack["split"].isin({"train", "search_validation"})].copy()
    search_split["split"] = "train_full"  # treat all search rows as training
    holdout_split = split_pack[split_pack["split"] == "milestone_holdout"].copy()

    combined_split = pd.concat([search_split, holdout_split], ignore_index=True)
    combined_frame = pd.concat([search_frame, holdout_frame], ignore_index=True)

    hyperparameters = {k: v for k, v in model_cfg.items() if k not in {"feature_inclusions", "feature_exclusions"}}

    # Apply feature builder if specified
    feature_builder_module = hyperparameters.pop("feature_builder_module", None)
    if feature_builder_module:
        import importlib
        builder = importlib.import_module(feature_builder_module)
        combined_frame = builder.build_features(combined_frame)

    model_result = dispatch_model(
        frame=combined_frame,
        split_frame=combined_split,
        model_family=model_family,
        target_strategy=target_strategy,
        train_split="train_full",
        score_splits=("milestone_holdout",),
        hyperparameters=hyperparameters,
        feature_inclusions=model_cfg.get("feature_inclusions"),
        feature_exclusions=model_cfg.get("feature_exclusions") or None,
        model_script_path=model_script_path,
        allow_holdout_split=True,
        target_mode=target_mode,
    )

    holdout_preds = model_result.predictions[model_result.predictions["split"] == "milestone_holdout"]
    if holdout_preds.empty:
        raise ValueError("No holdout rows in milestone predictions — check split pack")

    ho_actual_col, ho_predicted_col = prediction_target_columns(holdout_preds, target_mode)
    sv_actual_col, sv_predicted_col = prediction_target_columns(sv_only, target_mode)
    ho_metrics = full_metric_panel(
        holdout_preds[ho_actual_col],
        holdout_preds[ho_predicted_col],
        holdout_preds["exposure"],
        tweedie_power=config.tweedie_power,
        target_mode=target_mode,
    )
    sv_metrics = full_metric_panel(
        sv_only[sv_actual_col],
        sv_only[sv_predicted_col],
        sv_only["exposure"],
        tweedie_power=config.tweedie_power,
        target_mode=target_mode,
    )

    # Calibration on holdout
    holdout_preds_for_diag = holdout_preds.copy()
    holdout_preds_for_diag["split"] = "milestone_holdout"
    try:
        diag = compute_diagnostics(holdout_preds_for_diag, eval_split="milestone_holdout", target_mode=target_mode)
        cal_rows = diag.get("calibration_by_pred_decile", [])
        cal_lines = [
            f"| Decile | Pred {spec.rate_label} | Actual {spec.rate_label} | Actual/Pred |",
            "|--------|--------:|----------:|------------:|",
        ]
        for row in cal_rows:
            cal_lines.append(
                f"| {row.get('decile','?')} | {row.get('pred_rate', row.get('pred_pp', 0)):.4f} | "
                f"{row.get('actual_rate', row.get('actual_pp', 0)):.4f} | {row.get('ratio', 0):.4f} |"
            )
        calibration_table = "\n".join(cal_lines)
    except Exception:
        calibration_table = "*(calibration diagnostics unavailable)*"

    report_text = _REPORT_TEMPLATE.format(
        promotion_id=promotion_id,
        date=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        champion_id=champion_id,
        model_family=model_family,
        target_mode=target_mode,
        rate_label=spec.rate_label,
        sv_tweedie=sv_metrics["tweedie_deviance_p15"],
        ho_tweedie=ho_metrics["tweedie_deviance_p15"],
        gap_tweedie=ho_metrics["tweedie_deviance_p15"] - sv_metrics["tweedie_deviance_p15"],
        sv_gini=sv_metrics["gini_weighted"],
        ho_gini=ho_metrics["gini_weighted"],
        gap_gini=ho_metrics["gini_weighted"] - sv_metrics["gini_weighted"],
        sv_dl=sv_metrics["double_lift_slope"],
        ho_dl=ho_metrics["double_lift_slope"],
        gap_dl=ho_metrics["double_lift_slope"] - sv_metrics["double_lift_slope"],
        sv_pa=sv_metrics["predicted_to_actual_ratio"],
        ho_pa=ho_metrics["predicted_to_actual_ratio"],
        gap_pa=ho_metrics["predicted_to_actual_ratio"] - sv_metrics["predicted_to_actual_ratio"],
        calibration_table=calibration_table,
    )
    report_path.write_text(report_text, encoding="utf-8")

    summary = {
        "promotion_id": promotion_id,
        "champion_id": champion_id,
        "model_family": model_family,
        "target_mode": target_mode,
        "status": "completed",
        "search_validation_metrics": sv_metrics,
        "holdout_metrics": ho_metrics,
        "sv_to_holdout_tweedie_gap": ho_metrics["tweedie_deviance_p15"] - sv_metrics["tweedie_deviance_p15"],
        "sv_to_holdout_gini_gap": ho_metrics["gini_weighted"] - sv_metrics["gini_weighted"],
        "report_path": str(report_path),
    }
    write_json(json_path, summary)
    return summary


def _artifact_path(config: ProjectConfig, experiment_id: str, artifact_type: str) -> Path:
    for artifact in list_artifacts(config.registry_path, experiment_id):
        if artifact["artifact_type"] == artifact_type:
            return Path(artifact["path"])
    raise FileNotFoundError(f"Experiment {experiment_id} has no {artifact_type!r} artifact")


def manual_evaluate_on_holdout(config: ProjectConfig, experiment_id: str) -> dict[str, Any] | None:
    """Trigger milestone evaluation for any experiment (not just a promotion)."""

    promotion_id = f"manual_{experiment_id}"
    return evaluate_on_holdout(config, experiment_id, promotion_id)
